version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: docker_postgres
    restart: always
    environment:
      POSTGRES_USER: promocode_user
      POSTGRES_PASSWORD: promocode_password
      POSTGRES_DB: promocode_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: docker_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

  dockerapp:
    build:
      context: ./DockerBlazor
      dockerfile: Dockerfile
    container_name: docker_blazor_app
    restart: always
    ports:
      - "5050:80"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=promocode_db;Username=promocode_user;Password=promocode_password

volumes:
  postgres_data:
